stages:
  - build
  - test

image: maven:3.9-eclipse-temurin-17

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn test